swagger: '2.0'
info:
  title: Service Qualification API
  description: >-
    The Service Qualification API allows you to check the service types
    available at a particular address
  version: 1.0.0
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: private-sapi.telstra.com
basePath: /v1/contract/eligibility/service-qualification
schemes:
  - https
security:
  - OAuth2:
      - TWSERVICEQUALIFICATION
paths:
  /simple-sq-details:
    get:
      operationId: Retrieve Simple Service Qualification
      summary: 'Get simple services available at the address '
      description: Get NBN Serviceability details from NBN Co based on the address id
      produces:
        - application/json
      parameters:
        - name: Authorization
          in: header
          description: >-
            A header in the format 'Bearer {access_token}' - get the token by
            using the OAuth API with the scope 'TWSERVICEQUALIFICATION'
          type: string
          required: true
        - name: addressId
          in: query
          description: >-
            This is the Address ID for which the sevice details will be
            returned.
          type: string
          required: true
        - name: customerAuthorityDate
          in: query
          description: >-
            Date on which end customer has provided an authority to the Service
            Provider.
          type: string
          required: false
        - name: tc2Required
          in: query
          description: >-
            If this flag is set, additional information about the orderable TC2
            capacity is sent as well as the copper pair eligible for TC2. TC4
            speeds and capacity will not be returned.
          type: boolean
          required: false
      tags:
        - Service Qualification
      responses:
        '200':
          description: Successful return of the message.
          schema:
            $ref: '#/definitions/serviceDetailsResponse'
        '400':
          description: Invalid or missing request parameters.
          schema:
            $ref: '#/definitions/serviceDetailsApigeeError'
        '401':
          description: >-
            The calling IP address or the Client Certificate are not Authorized
            to call the API.
          schema:
            $ref: '#/definitions/serviceDetailsApigeeError'
        '404':
          description: The requested URI or resource does not exist.
          schema:
            $ref: '#/definitions/serviceDetailsSystemError'
        '429':
          description: Too many requests in a given amount of time.
          schema:
            $ref: '#/definitions/serviceDetailsError'
        '500':
          description: >-
            There was an Internal Server Error occurring on the API. Use the
            correlation ID in the Response Body to troubleshoot.
          schema:
            $ref: '#/definitions/serviceDetailsError'
      security: []
securityDefinitions:
  OAuth2:
    type: oauth2
    tokenUrl: 'https://private-sapi.telstra.com/application/tw/v1/oauth/token'
    flow: application
    scopes:
      TWSERVICEQUALIFICATION: OAuth scope for the Service Qualification API
definitions:
  serviceDetailsResponse:
    type: object
    required:
      - code
      - status
      - time
      - data
      - request
      - correlationId
      - allocatedQuotaPerHour
      - currentUsagePerHour
      - allocatedQuotaPerDay
      - currentUsagePerDay
    properties:
      code:
        type: integer
        format: int32
        description: Response code for the message
      status:
        type: integer
        format: int32
        description: HTTP status code
      time:
        type: string
        format: date-time
        description: The date and time when the message was received by recipient.
      data:
        type: object
        required:
          - addressId
        properties:
          addressId:
            type: string
            description: Address id
          unconditionedLocalLoop:
            type: array
            description: Unbundled LoopBack Details
            items:
              type: object
              properties:
                nbnResourceId:
                  type: string
                  description: Copper Pair Identifier
                unconditionedLocalLoopId:
                  type: string
                  description: ULL ID
                serviceProviderId:
                  type: string
                  description: Service Provider ID
                demandType:
                  type: string
                  description: Demand Type
                maxDownstreamSpeed:
                  type: string
                  description: Max Downstream Speed
                maxUpstreamSpeed:
                  type: string
                  description: Max Upstream Speed
          productResourceIdentifierDetails:
            type: object
            description: Product Resource Identifier Details
            properties:
              productResourceIdentifierID:
                type: string
                description: Product Resource IdentifierID
              nbnPriorityAssist:
                type: string
                description: NBN Priority Assist
              serviceProviderId:
                type: string
                description: Service Provider Id
              maxDownstreamSpeed:
                type: string
                description: Maximum Downstream Speed
              maxUpstreamSpeed:
                type: string
                description: Maximum Upstream Speed
              refCopperPairID:
                type: string
                description: Reference CopperPair ID
              portLinkage:
                type: string
                description: portLinkage
              uniPortType:
                type: string
                description: Uni Port Type
              portId:
                type: string
                description: Port ID
              refNTD:
                type: string
                description: 'Reference of NTD ID (FW, FTTP or HFC)'
              portDetails:
                type: string
                description: Port Details
              batteryPowerStatus:
                type: string
                description: Battery Power Status
              batteryInstallDate:
                type: string
                description: Battery Install Date
              batteryMonitoringStatus:
                type: string
                description: Battery Monitoring Status
              ntdLoc:
                type: string
                description: NTD Location
              ntdInstallDate:
                type: string
                description: NTD Install Date
              ntdType:
                type: string
                description: NTD Type
              ntdPowerType:
                type: string
                description: NTD Power Type
          resourceDetails:
            type: array
            description: Resource Details
            items:
              properties:
                ntdId:
                  type: string
                  description: NTD ID
                ntdLoc:
                  type: string
                  description: NTD Location
                ntdInstallDate:
                  type: string
                  description: NTD Install Date
                ntdType:
                  type: string
                  description: NTD Type
                ntdPowerType:
                  type: string
                  description: NTD Power Type
                batteryPowerUnit:
                  type: string
                  description: Battery Power Unit
                powerSupplywithBatteryBackupInstallDate:
                  type: string
                  description: Power Supply with Battery Backup Install Date
                uniPortType:
                  type: string
                  description: Uni Port Type
                portDetails:
                  type: array
                  description: Port Details
                  items:
                    properties:
                      portId:
                        type: string
                        description: PortId
                      portStatus:
                        type: string
                        description: Port Status
          additionalTrafficClassAvailability:
            type: array
            description: Additional Traffic Class Availability
            items:
              properties:
                name:
                  type: string
                  description: name of the additional Traffic Class Availability from NBN
                value:
                  type: string
                  description: value of the additional Traffic Class Availability from NBN
          orderableTC2Capacity:
            type: object
            description: Optional  Orderable TC2 Capacity
            properties:
              maxBackhaul:
                type: string
                description: Max Backhaul TC2 Capacity
              maxSpareCopperPair:
                type: string
                description: Max Spare Copper Pair
              maxTransitioningCopperPair:
                type: string
                description: Max Transitioning Copper Pair
          serviceTypeQualifications:
            type: array
            description: serviceTypeQualifications
            required:
              - serviceType
              - readyForServiceDate
              - locationId
              - tc2EnabledCsa
              - status
              - statusReason
            items:
              properties:
                serviceType:
                  type: string
                  description: Service Type
                technologyType:
                  type: string
                  description: technologyType
                readyForServiceDate:
                  type: string
                  description: RFS Date
                serviceabilityClass:
                  type: string
                  description: serviceabilityClass
                newDevelopmentChargesApply:
                  type: string
                  description: NBN New Development Charges Apply
                locationId:
                  type: string
                  description: Location Id
                csaId:
                  type: string
                  description: CSA ID
                demandType:
                  type: string
                  description: Demand Type
                providerResources:
                  type: array
                  description: List of Copper Pair Detail
                  items:
                    properties:
                      resourceType:
                        type: string
                        description: Resource Type
                      id:
                        type: string
                        description: Copper Pair Id
                      status:
                        type: string
                        description: Status
                      serviceabilityClass:
                        type: string
                        description: Serviceability Class
                characteristics:
                  type: array
                  description: Characteristics of the Calling and Internet Services
                  items:
                    properties:
                      name:
                        type: string
                        description: >-
                          Names of the Characteristics for Calling and Internet.
                          Valid value for Calling :  · Telephony Type Valid
                          values for Internet : · TC4 Downstream Upper Rate ·
                          TC4 Downstream Lower Rate · TC4 Upstream Upper Rate ·
                          TC4 Upstream Lower Rate
                      value:
                        type: string
                        description: Values for Characteristics of Calling and Internet
                serviceTransferIndicator:
                  type: string
                  description: Service Transfer and ULL Transition Applicability Indicator
                tc2EnabledCsa:
                  type: string
                  description: TC2 enabled CSA
                priorityAssistApplicable:
                  type: string
                  description: NBN Priority Status
                appointmentRequired:
                  type: string
                  description: Appointment Required Indicator
                status:
                  type: string
                  description: Availability Status
                statusReason:
                  type: string
                  description: Available Status Reason
          scheduledDates:
            type: object
            description: scheduledDates
            properties:
              ceaseSaleDate:
                type: string
                description: Cease Sale Date
              disconnectionDate:
                type: string
                description: Disconnection Date
              orderStabilityPeriodDate:
                type: string
                description: Order Stability PeriodDate
          messages:
            type: array
            description: messages
            items:
              properties:
                code:
                  type: string
                  description: code
                message:
                  type: string
                  description: Message
        description: The response data received by the client.
      request:
        type: object
        description: Request object.
        required:
          - params
          - data
          - path
          - method
          - requestId
          - correlationId
        properties:
          params:
            type: object
            description: Request Param sent as part of the request.
            properties:
              addressId:
                type: string
                description: Telstra address id sent as part of the request.
              customerAuthorityDate:
                type: string
                description: customerAuthorityDate sent as part of the request.
              tc2Required:
                type: boolean
                description: tc2Required sent as part of the request.
          data:
            type: object
          path:
            type: string
            description: Request path.
          method:
            type: string
            description: Request method.
          requestId:
            type: string
            description: Unique request number.
          correlationId:
            type: string
            description: Correlation ID sent as part of the request.
      correlationId:
        type: string
        description: Correlation id of the message receieved
      allocatedQuotaPerHour:
        type: integer
        description: Allocated Quota per hour
      currentUsagePerHour:
        type: integer
        description: Current quota usage per hour
      allocatedQuotaPerDay:
        type: integer
        description: Allocated Quota per day
      currentUsagePerDay:
        type: integer
        description: Current quota usage per day
    example:
      code: 200
      status: 200
      time: '2018-02-19T16:10:45+11:00'
      data:
        addressId: '65512548'
        serviceTypeQualifications:
          - serviceType: Calling
            technologyType: Fibre To The Node
            readyForServiceDate: '2009-10-11'
            serviceabilityClass: '13'
            newDevelopmentChargesApply: 'No'
            locationId: LOC171118080143
            csaId: CSA300000000412
            demandType: Standard Install
            providerResources:
              - resourceType: Copper Pair
                id: New Path
                status: ''
                serviceabilityClass: '12'
            characteristics:
              - name: Telephony Type
                value: IP Telephony
            serviceTransferIndicator: YN
            tc2EnabledCsa: true
            priorityAssistApplicable: 'No'
            appointmentRequired: 'Yes'
            status: Available
            statusReason: >-
              NBN Technology at this location only supports IP Telephony and NBN
              Lead-In is required to provide the services
          - serviceType: Internet
            technologyType: Fibre To The Node
            readyForServiceDate: '2009-10-11'
            serviceabilityClass: '13'
            newDevelopmentChargesApply: 'No'
            locationId: LOC171118080143
            csaId: CSA300000000412
            demandType: Standard Install
            providerResources:
              - resourceType: Copper Pair
                id: New Path
                status: ''
                serviceabilityClass: '12'
            characteristics:
              - name: TC4 Downstream Upper Rate
                value: 25 Mbps
              - name: TC4 Downstream Lower Rate
                value: ''
              - name: TC4 Upstream Upper Rate
                value: 5 Mbps
              - name: TC4 Upstream Lower Rate
                value: ''
            serviceTransferIndicator: YN
            appointmentRequired: 'Yes'
            status: Available
            statusReason: >-
              NBN Internet is serviceable at this address and NBN Lead-In is
              required to provide the services
        additionalTrafficClassAvailability:
          - name: High Speed TC2 (greater or equal to 20Mbps)
            value: 'No'
          - name: TC2
            value: 'No'
          - name: NCAS TC2 5Mbps Capacity
            value: 'No'
          - name: NCAS TC2 10Mbps Capacity
            value: 'No'
          - name: NCAS TC2 20Mbps Capacity
            value: 'No'
          - name: NCAS TC2 30Mbps Capacity
            value: 'No'
          - name: NCAS TC2 40Mbps Capacity
            value: 'No'
          - name: NCAS TC4 High Speed Tiers (greater or equal to 250Mbps)
            value: 'No'
          - name: NCAS TC1 High Speed Tiers (greater or equal to 0.3Mbps)
            value: 'No'
          - name: NCAS TC1 High Speed Tiers (greater or equal to 2Mbps)
            value: 'Yes'
          - name: Multicast
            value: 'No'
        messages:
          - code: SQNTT002
            message: The dates cannot be retrieved due to downstream errors
        scheduledDates:
          ceaseSaleDate: ''
          disconnectionDate: ''
          orderStabilityPeriodDate: ''
      request:
        params:
          addressId: '65512548'
        data: {}
        path: /service-addresses
        method: GET
        requestId: 4a0cfb0e-c19a-4742-9171-d3832487dfab
        correlationId: ebf6c05a-30c1-4dae-b6e6-aefb11c8ce43
      correlationId: ebf6c05a-30c1-4dae-b6e6-aefb11c8ce43
      currentUsagePerDay: 4
      allocatedQuotaPerDay: 500
      currentUsagePerHour: 4
      allocatedQuotaPerHour: 200
  serviceDetailsError:
    type: object
    required:
      - status
      - code
      - message
      - errors
      - allocatedQuotaPerHour
      - currentUsagePerHour
      - allocatedQuotaPerDay
      - currentUsagePerDay
    properties:
      status:
        type: integer
        description: The error code received by the client.
      code:
        type: integer
        description: The error status code received by the client.
      message:
        type: string
      errors:
        description: The error details received by the client
        type: array
        items:
          required:
            - code
            - message
          properties:
            code:
              type: integer
            message:
              type: string
      allocatedQuotaPerHour:
        type: integer
        description: Allocated Quota per hour
      currentUsagePerHour:
        type: integer
        description: Current quota usage per hour
      allocatedQuotaPerDay:
        type: integer
        description: Allocated Quota per day
      currentUsagePerDay:
        type: integer
        description: Current quota usage per day
    example:
      status: 500
      code: 500
      message: Unable to process the request
      errors:
        - code: 500
          message: Unable to process the request
      allocatedQuotaPerHour: 200
      currentUsagePerHour: 0
      allocatedQuotaPerDay: 500
      currentUsagePerDay: 4
  serviceDetailsApigeeError:
    type: object
    properties:
      status:
        type: integer
        description: The error code received by the client.
      code:
        type: integer
        description: The error status code received by the client.
      message:
        type: string
      errors:
        description: The error details received by the client
        type: array
        items:
          required:
            - code
            - message
          properties:
            code:
              type: integer
            message:
              type: string
    example:
      status: 401
      code: 401
      message: Invalid or no credentials passed in the request
      errors:
        - code: 401
          message: Invalid OAuth token
  serviceDetailsSystemError:
    type: object
    properties:
      status:
        type: integer
        description: The error code received by the client.
      code:
        type: integer
        description: The error status code received by the client.
      message:
        type: string
      errors:
        description: The error details received by the client
        type: array
        items:
          required:
            - code
            - message
          properties:
            code:
              type: integer
            message:
              type: string
    example:
      status: 404
      code: 404
      message: Not found
      errors:
        - code: 404
          message: 'The requested URI or resource does not exist. '
